### ISSUE TITLE
Run websub.rocks locally

### ISSUE THREAD

**Issue by owickstrom** [aaronpk/websub.rocks#10]
Hey!

First off, thanks for this project, it is really helpful!

Second, is it possible to host this locally and run against a websub client implementation on localhost? What would be useful for quick debugging, not having to expose the server on the Internet.

If so, could you perhaps add some instructions on how to do that? I couldn't find any, and I'm not familiar with Composer. I can dig into those docs, but it would be nice with a small summary on how to start it up. If I get it up, I can submit a PR.

Thanks!

**Comment by aaronpk** [comment]
Sure, I can make this a little easier to deploy locally. There will still be a couple steps involved since you'll have to create a MySQL database for it. 

The other option is you can use a service like https://ngrok.com or create an SSH tunnel to make a public address for your localhost service.

**Comment by owickstrom** [comment]
Yeah, but that's OK! :) Thanks!

**Comment by aaronpk** [comment]
Alright, I've added installation instructions to the readme file, and released a package where you can install all the files without needing to set up Composer.

There are still a few moving parts to getting it running, so you might be better off using ngrok.com or an SSH tunnel, but at least now there are instructions for how to run it locally! Thanks!

**Comment by owickstrom** [comment]
Thank you @aaronpk, I'll try these instructions out. :+1:

**Comment by owickstrom** [comment]
I set up port forwarding at home for now, and some DynDNS service.
