### ISSUE TITLE
Publisher test: server returns HTTP 500 during intent verification phase

### ISSUE THREAD

**Issue by dannmartens** [aaronpk/websub.rocks#24]
I am investigating why notifications are not getting through in this test:

![image](https://user-images.githubusercontent.com/263133/95351043-13460b80-08c1-11eb-9554-1e8c24980028.png)

In my hub logs, I see that the request to /publisher/callback fails, with a HTTP 500:
```
https://websub.rocks:443 "GET /publisher/callback?token=ClIQLYdYwbJWypHye2Md&hub.mode=subscribe&hub.topic=https%3A%2F%2Fwww.example.com%2F&hub.challenge=da7e7403-bf5c-4d3e-bd15-f33305d5453b&hub.lease_seconds=7200 HTTP/1.1" 500 None
```
(I swapped out my hub's URL with www.example.com)

This causes a failure of the subscriber intent verification at the hub-side, as in "5.3 Hub Verifies Intent of the Subscriber."

**Comment by aaronpk** [comment]
Sorry about that, looks like a change in an underlying library that I needed to handle. Should be working now!

**Comment by dannmartens** [comment]
Whoa, talk about a speed delivery!

![IWhoa](https://media.giphy.com/media/n34uyi4r6HAQM/giphy.gif)

I tested it again, and now the notification goes all the way through!

Excellent!
