### ISSUE TITLE
Email delivery failing

### ISSUE THREAD

**Issue by tonyg** [aaronpk/websub.rocks#3]
Lightly anonymized log entry from my mail server:

> Nov 19 20:07:20 MACHINENAME postfix/smtpd[14486]: NOQUEUE: reject: RCPT from mail-s68.mailgun.info[184.173.153.196]: 554 5.1.8 <bounce+fdcdec.0cce7-MYEMAILADDR@mail.pubsub.rocks>: Sender address rejected: Domain not found; from=<bounce+fdcdec.0cce7-MYEMAILADDR@mail.pubsub.rocks> to=<MYEMAILADDR> proto=ESMTP helo=<mail-s68.mailgun.info>

The problem appears to be a missing DNS record (of some kind) for `mail.pubsub.rocks`?

**Comment by aaronpk** [comment]
Looks like Mailgun recommends using a subdomain like `mail.pubsub.rocks`, but then doesn't tell you to set a DNS record for that subdomain other than the TXT records it uses. I'm guessing some mail servers check for an A/CNAME record of the subdomain as an anti-spam thing. 

I moved the site to `websub.rocks` and set up the DNS again, this time with an A record on `mail.websub.rocks`, so this should be fixed now!

**Comment by tonyg** [comment]
Yes, perfect! Works like a charm. Thank you!

**Comment by aaronpk** [comment]
Glad to hear, thanks! Also fyi, there isn't actually any extra functionality after you log in right now. In the future, that's going to be how you submit an implementation report, the same way it works on https://micropub.rocks/
