### ISSUE TITLE
Rel=Self parsing looks at the atom entries instead of the feed

### ISSUE THREAD

**Issue by kevinmarks** [aaronpk/websub.rocks#5]
When I use https://mastodon.social/users/kevinmarks.atom it gives an error about the self, but it is correct at the feed level.

**Comment by aaronpk** [comment]
This is the error when I try that URL, is that different from what you see?

![screenshot 2016-12-01 08 35 43](https://cloud.githubusercontent.com/assets/113001/20802532/2dc15d4a-b7a1-11e6-9c03-dc5d4ec7a421.png)

**Comment by aaronpk** [comment]
ah nevermind, I re-read the issue name and now I understand the problem :-)
