### ISSUE TITLE
if 2 hubs are specified, it sees the second one only

### ISSUE THREAD

**Issue by kevinmarks** [aaronpk/websub.rocks#6]
https://mastodon.social/users/kevinmarks.atom has 

````
  <link rel="hub" href="https://mastodon.social/api/push"/>
  <link rel="hub" href="https://pubsubhubbub.superfeedr.com"/>
````

and only the superfeedr one is seen.

**Comment by aaronpk** [comment]
The spec says:

> If more than one URL is specified, it is expected that the publisher pings each of these URLs, so the subscriber may subscribe to one or more of these.

It was a side effect of this implementation that the second one in the list is used. I changed it to use the first in the list, so at least that should be less unexpected.

**Comment by kevinmarks** [comment]
It might make sense to test both and report on each - if other subscription
implementations vary which they choose it could make problems with the
other one.

**Comment by kevinmarks** [comment]
Also, when testing subscribers, see which they choose from multiple choices
and document that. If they are consistent about first/last could change the
spec to match.

**Comment by aaronpk** [comment]
I'll make it show an option to choose which hub to test when it finds more than one

**Comment by aaronpk** [comment]
Good idea: #8
